Areas/cafeBlue/Controllers/MealController.cs
using AppService.Areas.cafeBlue.Models;
using CafeBlue;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;

namespace AppService.Areas.cafeBlue.Controllers
{
    public class MealController : Controller
    {
        //
        // GET: /cafeBlue/Meal/

        public ActionResult Index()
        {
            ProductModel model = new ProductModel();   
            return View(model.getProduct("meal"));
        }

        [HttpPost]
        public ActionResult FileUpload(ProductsTable model,HttpPostedFileBase file)
        {         
            if (file!= null && file.ContentLength > 0)
            {
                var fileName = Path.GetFileName(file.FileName);
                var path = Path.Combine(Server.MapPath("~/Areas/cafeBlue/Images/"), fileName);
                file.SaveAs(path);
            }
          
            if(file != null)
                model.ProductImage = System.IO.Path.GetFileName(file.FileName);

            ProductModel pmodel = new ProductModel();
            pmodel.newProduct(model);

            return RedirectToAction("Index",model.ProductCatigory);
        }

        public JsonResult ManageProduct(string productName,string cati)
        {
            return Json(new ProductModel().findProduct(cati,productName), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult UpdateProduct(ProductsTable data)
        {
            new ProductModel().editProduct(data);           
            return Json(null);
        }

        [HttpPost]
        public JsonResult NameStatus(string name,string cati)
        {
            bool state = false;
            state = ProductModel.nameExist(name,cati);
            return Json(state);
        }

        [HttpPost]
        public JsonResult RemoveProd(string name,string cati)
        {
            string done = "done";
            ProductModel meal = new ProductModel();
            meal.removeProduct(name, cati);
            return Json(done);
        }
    }    
}

Areas/cafeBlue/Views/Shared/_ProductControlPartial.cshtml
@model string
<div class="box box-primary" style="position:relative;">
    <div class="box-header ui-sortable-handle" style="cursor:move;">

    </div>
    <a class="btn btn-app" id="modal-29791-new-meal" role="button" href="#modal-container-29791-new" data-toggle="modal" onclick="return setMode('@Model');">
        <i class="fa fa-barcode"></i>
        New Product
    </a>
    <a class="btn btn-app" id="modal-29792-manage" role="button" href="#modal-container-29792-manage" data-toggle="modal" onclick="return setMode('@Model');">
        <i class="fa fa-edit"></i>
        Manage Product
    </a>
    <a class="btn btn-app" id="modal-29793-remove" role="button" href="#modal-container-29793-remove" data-toggle="modal" onclick="return setMode('@Model');">
        <i class="fa fa-remove"></i>
        Delete Product
    </a>
</div>

Areas/cafeBlue/Views/Shared/_dataTablePartial.cshtml
@model IEnumerable<CafeBlue.ProductsTable>
@{
    List<SelectListItem> items = new List<SelectListItem>();
}

<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Meal</h3>
            </div><!-- /.box-header -->
            <div class="box-body">
                <table class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <td>#</td>
                            <td>Name</td>
                            <td>Description</td>
                            <td>Small Price</td>
                            <td>Medium Price</td>
                            <td>Large Price</td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (CafeBlue.ProductsTable m in @Model)
                        {
                            <tr>
                                <td>@m.Id</td>
                                <td>@m.ProductName</td>
                                <td>@m.Description</td>
                                <td>$@m.smallprice</td>
                                <td>$@m.medprice</td>
                                <td>$@m.largeprice</td>
                            </tr>

                            items.Add(new SelectListItem
                            {
                                Text = m.ProductName,
                                Value = m.ProductName
                            });
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@Html.Partial("_manageProductPartial", items)
@Html.Partial("_newProductPartial", new CafeBlue.ProductsTable())
@Html.Partial("_removePartial", items)

Areas/cafeBlue/Views/Shared/_manageProductPartial.cshtml
@model IEnumerable<SelectListItem> 

@using (Html.BeginForm("Index", "Meal", FormMethod.Post, new { Id = "newProduct" }))
{
    <div class="modal fade" id="modal-container-29792-manage" role="dialog" aria-hidden="true" aria-labelledby="myModalLabel">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button class="close" aria-hidden="true" type="button" data-dismiss="modal">
                        ×
                    </button>
                    <h4 class="modal-title" id="myModalLabelNewProduct">
                        Manage Product
                    </h4>
                </div>
                <div class="modal-body">
                    @Html.DropDownList("products", Model, new { id = "prodOption", onChange = "return findProduct();" })  
<br/>
                    <table>
                        <tr>
                            <td style="width:10px;">
                                Product Name:
                            </td>
                            <td>
                                @Html.TextBox("productName_manage")
                            </td>
                            <td id="pn" style="color:red;">
                                <input type="text" id="proCat_manage" value="" style="visibility:collapse;"/>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                small. Price:
                            </td>
                            <td>
                                @Html.TextBox("smallprice_manage")
                            </td>
                            <td id="sp" style="color:red;"></td>
                        </tr>
                        <tr>
                            <td>
                                Med. Price:
                            </td>
                            <td>
                                @Html.TextBox("medprice_manage")
                            </td>
                            <td id="mp" style="color:red;"></td>
                        </tr>
                        <tr>
                            <td>
                                Large. Price:
                            </td>
                            <td>
                                @Html.TextBox("largeprice_manage")
                            </td>
                            <td id="lp" style="color:red;"></td>
                        </tr>
                        <tr>
                            <td>
                                Description:
                            </td>
                            <td>
                                @Html.TextArea("description_manage")
                            </td>
                            <td id="descr" style="color:red;"></td>
                        </tr>
                    </table>    
                </div>
                <div class="modal-footer">
                    <button id="btn-close" class="btn btn-default" type="button" data-dismiss="modal">
                        Close
                    </button>
                    <a id="save_manage" class="btn btn-primary" data-dismiss="modal">
                        Save
                    </a>
                </div>
            </div>
        </div>
    </div>
}

Areas/cafeBlue/Views/Shared/_newProductPartial.cshtml
@using (Html.BeginForm("FileUpload", "Meal", FormMethod.Post, new { Id = "newProdform", enctype = "multipart/form-data" }))
{
    <div class="modal fade" id="modal-container-29791-new" role="dialog" aria-hidden="true" aria-labelledby="myModalLabel">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button class="close" aria-hidden="true" type="button" data-dismiss="modal">
                        ×
                    </button>
                    <h4 class="modal-title" id="myModalLabelNewProduct" >
                        New Product
                    </h4>
                </div>
                <div class="modal-body">    
                    <div id="newmeals">                       
                        <table>   
                            <tr>
                                <td style="width:10px;">
                                    Product Name:
                                </td>
                                <td>                                           
                                    <input type="text" id="ProductName" name="ProductName" onblur="return validateProductName();" />                            
                                </td>
                                <td style="color:red;">
                                    <input id="proCat" name="ProductCatigory" type="text" value="" style="visibility:hidden;"/>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    small. Price:
                                </td>
                                <td>
                                    @Html.TextBox("smallprice",null, new {id="smallprice" })
                                </td>
                                <td id="sp" style="color:red;"></td>
                            </tr>                         
                            <tr>
                                <td>
                                    Med. Price:
                                </td>
                                <td>
                                    @Html.TextBox("medprice",null, new { id="medprice"})
                                </td>
                                <td id="mp" style="color:red;"></td>
                            </tr>
                            <tr>
                                <td>
                                    Large. Price:
                                </td>
                                <td>
                                    @Html.TextBox("largeprice",null, new {id="largeprice" })
                                </td>
                                <td id="lp" style="color:red;"></td>
                            </tr>
                            <tr>
                                <td>Image:</td>
                                <td>
                                    <input name="file" type="file" accept="image/*" id="file" onchange="return setpreview();" />
                                </td>
                                <td id="uimg" style="color:red;"></td>
                            </tr>
                            <tr>
                                <td>
                                    Description:
                                </td>
                                <td>
                                    @Html.TextArea("Description", new {id="description" })
                                </td>
                                <td id="descr" style="color:red;"></td>
                            </tr>
                        </table>
                                  
                        <img width="180" height="180" style="margin-left:400px;margin-top:-200px;" class="img-thumbnail" alt="Bootstrap Image Preview" id="preView"
                             src="~/Images/1450012368_Burger.png"/>                        
                    </div>                  
                </div>
                <div class="modal-footer">
                    <button id="btn-close" class="btn btn-default" type="button" data-dismiss="modal">
                        Close
                    </button>
                  
                    <a href="javascript:validateNewForm();" class="btn btn-primary">
                        Save
                    </a>
                </div>
            </div>
        </div>
    </div>
}

Areas/cafeBlue/Views/Shared/_removePartial.cshtml
@model IEnumerable<SelectListItem>

<div class="modal fade" id="modal-container-29793-remove" role="dialog" aria-hidden="true" aria-labelledby="myModalLabel">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button class="close" aria-hidden="true" type="button" data-dismiss="modal">
                    ×
                </button>
                <h4 class="modal-title" id="myModalLabel">
                    Delete Product
                </h4>
            </div>
            <div class="modal-body">
                <table>
                    <tr>
                        <td style="width:200px;">
                            Meals:
                        </td>
                        <td>
                            @Html.DropDownList("prod", Model, new { id = "prod" })
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Type the name of the meal
                        </td>
                        <td>
                            @Html.TextBox("prodname", null, new { id = "prodname", Style = "color:red;" })
                        </td>
                    </tr>
                </table>
            </div>
            <div class="modal-footer">
                <button id="btn-close" class="btn btn-default" type="button" data-dismiss="modal">
                    Close
                </button>
                <button onclick="return validateDelete();" class="btn btn-danger">
                    Delete
                </button>
            </div>
        </div>
    </div>
</div> 